// <auto-generated />
using System;
using IDGenWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDGenWebsite.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AcademicSessionsClasses", b =>
                {
                    b.Property<Guid>("AcademicSessionsSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AcademicSessionsSourcedId", "ClassesSourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.ToTable("AcademicSessionsClasses");
                });

            modelBuilder.Entity("IDGenWebsite.Models.AcademicSessions", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("ParentSourcedId");

                    b.ToTable("AcademicSessions");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Classes", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CourseSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SchoolSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("CourseSourcedId");

                    b.HasIndex("SchoolSourcedId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Courses", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrganizationSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolYearSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("OrganizationSourcedId");

                    b.HasIndex("SchoolYearSourcedId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Enrollments", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Class_SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Organizations_SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("User_SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourcedId");

                    b.HasIndex("Class_SourcedId");

                    b.HasIndex("Organizations_SourcedId");

                    b.HasIndex("User_SourcedId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Grades", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoursesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsersSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.HasIndex("CoursesSourcedId");

                    b.HasIndex("UsersSourcedId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("IDGenWebsite.Models.IDRequestModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePrinted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBeenPrinted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IDRequests");
                });

            modelBuilder.Entity("IDGenWebsite.Models.IdTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackBottomColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackInfoLineOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackInfoLineThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackInfoLineTwo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackMiddleColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackTopColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackTopLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontBottomColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontMiddleColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontTopColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontTopLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("IdTemplates");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Metadatas", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademicSessionsSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EnrollmentsSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationsSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ResourcesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsersSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("AcademicSessionsSourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.HasIndex("CoursesSourcedId");

                    b.HasIndex("EnrollmentsSourcedId");

                    b.HasIndex("OrganizationsSourcedId");

                    b.HasIndex("ResourcesSourcedId");

                    b.HasIndex("UsersSourcedId");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Organizations", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UsersSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourcedId");

                    b.HasIndex("ParentSourcedId");

                    b.HasIndex("UsersSourcedId");

                    b.ToTable("Orgs");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Periods", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Resources", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Importance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorResourceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.HasIndex("CoursesSourcedId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("IDGenWebsite.Models.SettingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SettingDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("IDGenWebsite.Models.SubjectCodes", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.HasIndex("CoursesSourcedId");

                    b.ToTable("SubjectCodes");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Subjects", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoursesSourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.HasIndex("ClassesSourcedId");

                    b.HasIndex("CoursesSourcedId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Users", b =>
                {
                    b.Property<Guid>("SourcedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnabledUser")
                        .HasColumnType("bit");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPicPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourcedId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AcademicSessionsClasses", b =>
                {
                    b.HasOne("IDGenWebsite.Models.AcademicSessions", null)
                        .WithMany()
                        .HasForeignKey("AcademicSessionsSourcedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany()
                        .HasForeignKey("ClassesSourcedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IDGenWebsite.Models.AcademicSessions", b =>
                {
                    b.HasOne("IDGenWebsite.Models.AcademicSessions", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSourcedId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Classes", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Courses", "Course")
                        .WithMany()
                        .HasForeignKey("CourseSourcedId");

                    b.HasOne("IDGenWebsite.Models.Organizations", "School")
                        .WithMany()
                        .HasForeignKey("SchoolSourcedId");

                    b.Navigation("Course");

                    b.Navigation("School");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Courses", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Organizations", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationSourcedId");

                    b.HasOne("IDGenWebsite.Models.AcademicSessions", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("SchoolYearSourcedId");

                    b.Navigation("Organization");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Enrollments", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", "Class")
                        .WithMany()
                        .HasForeignKey("Class_SourcedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDGenWebsite.Models.Organizations", "School")
                        .WithMany()
                        .HasForeignKey("Organizations_SourcedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDGenWebsite.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("User_SourcedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Grades", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", "Classes")
                        .WithMany("Grades")
                        .HasForeignKey("ClassesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Courses", "Courses")
                        .WithMany("Grades")
                        .HasForeignKey("CoursesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Users", null)
                        .WithMany("Grades")
                        .HasForeignKey("UsersSourcedId");

                    b.Navigation("Classes");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Metadatas", b =>
                {
                    b.HasOne("IDGenWebsite.Models.AcademicSessions", null)
                        .WithMany("Metadata")
                        .HasForeignKey("AcademicSessionsSourcedId");

                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ClassesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Courses", null)
                        .WithMany("Metadata")
                        .HasForeignKey("CoursesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Enrollments", null)
                        .WithMany("Metadata")
                        .HasForeignKey("EnrollmentsSourcedId");

                    b.HasOne("IDGenWebsite.Models.Organizations", null)
                        .WithMany("Metadata")
                        .HasForeignKey("OrganizationsSourcedId");

                    b.HasOne("IDGenWebsite.Models.Resources", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ResourcesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Users", null)
                        .WithMany("Metadata")
                        .HasForeignKey("UsersSourcedId");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Organizations", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Organizations", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentSourcedId");

                    b.HasOne("IDGenWebsite.Models.Users", null)
                        .WithMany("Organizations")
                        .HasForeignKey("UsersSourcedId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Periods", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany("Periods")
                        .HasForeignKey("ClassesSourcedId");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Resources", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany("Resources")
                        .HasForeignKey("ClassesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Courses", null)
                        .WithMany("Resources")
                        .HasForeignKey("CoursesSourcedId");
                });

            modelBuilder.Entity("IDGenWebsite.Models.SubjectCodes", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany("SubjectCodes")
                        .HasForeignKey("ClassesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Courses", null)
                        .WithMany("SubjectCodes")
                        .HasForeignKey("CoursesSourcedId");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Subjects", b =>
                {
                    b.HasOne("IDGenWebsite.Models.Classes", null)
                        .WithMany("Subjects")
                        .HasForeignKey("ClassesSourcedId");

                    b.HasOne("IDGenWebsite.Models.Courses", null)
                        .WithMany("Subjects")
                        .HasForeignKey("CoursesSourcedId");
                });

            modelBuilder.Entity("IDGenWebsite.Models.AcademicSessions", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Classes", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Metadata");

                    b.Navigation("Periods");

                    b.Navigation("Resources");

                    b.Navigation("SubjectCodes");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Courses", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Metadata");

                    b.Navigation("Resources");

                    b.Navigation("SubjectCodes");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Enrollments", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Organizations", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Resources", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("IDGenWebsite.Models.Users", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Metadata");

                    b.Navigation("Organizations");
                });
#pragma warning restore 612, 618
        }
    }
}
